name: CI - Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create .env file
        run: | 
          echo "${{secrets.ENV_FILE}}" > .env

      - name: Run Member & Auth Tests
        run: ./gradlew test --tests "com.bandchu.api.domain.member.*" -Dspring.profiles.active=test

      - name: Run Post Tests
        run: ./gradlew test --tests "com.bandchu.api.domain.posts.service.*" -Dspring.profiles.active=test



      #- name: Run Subscription Tests
      #  run: ./gradlew test --tests "com.bandchu.api.domain.subscription.controller.*" -Dspring.profiles.active=test

    #  - name: Run Artist Tests
    #    run: ./gradlew test --tests "com.bandchu.api.domain.artists.controller.*" -Dspring.profiles.active=test

   #   - name: Run Chat Tests
   #     run: ./gradlew test --tests "com.bandchu.api.domain.chat.controller.*" -Dspring.profiles.active=test

  #    - name: Run Album Tests
  #      run: ./gradlew test --tests "com.bandchu.api.domain.album.controller.*" -Dspring.profiles.active=test